<?php

/**
 * ProcessWire Configuration File
 *
 * Site-specific configuration for ProcessWire.
 * This config.php file was generated by the ProcessExportProfile module. 
 *
 * Please see the file /wire/config.php which contains all configuration options you may
 * specify here. Simply copy any of the configuration options from that file and paste
 * them into this file in order to modify them.
 *
 * ProcessWire 
 * Copyright (C) 2017 by Ryan Cramer
 * Licensed under MPL 2.0
 *
 * https://processwire.com
 *
 */

if(!defined("PROCESSWIRE")) die();

/*** SITE CONFIG *************************************************************************/

/**
 * Enable debug mode?
 *
 * Debug mode causes additional info to appear for use during dev and debugging.
 * This is almost always recommended for sites in development. However, you should
 * always have this disabled for live/production sites.
 *
 * @var bool
 *
 */
	$config->debug = true;

	$config->prependTemplateFile = '_init.php';
	$config->maxUrlSegments = 7;
	$config->defaultAdminTheme = 'AdminThemeUikit';
	$config->rootURL = $rootURL;
	$config->urls->vendor = "vendor/";
	$config->urls->content = "$siteDir/templates/content/";
	$config->paths = clone $config->urls;
	$config->paths->root = $rootPath . '/';
	$config->paths->sessions = $config->paths->assets . "sessions/";
	$config->dplusdbname = "dpluso";
	$config->cgis = array(
		'default' => 'DPLUSO3',
		'whse' => 'DPLUSOWAREHOUSE3'
	);
	$config->cptechcustomer = 'cptech';
	$config->COMPANYNBR = '3';
	$config->companyfiles = "/var/www/html/data$config->COMPANYNBR/";
	$config->documentstorage = "/orderfiles/";
	$config->documentstoragedirectory = "/var/www/html/orderfiles/";
	$config->jsonfilepath = "/var/www/html/files/json$config->COMPANYNBR/";
	$config->directory = "";
	$config->directory_httpd = "dpluso";
	$config->filename = $_SERVER['REQUEST_URI'];
	$config->script = str_replace($config->urls->root, '', $_SERVER['SCRIPT_NAME']);
	$config->imagedirectory = '/img/product/';
	$config->imagefiledirectory  = '/var/www/html/img/product/';
	$config->imagenotfound = 'notavailable.png';
	$config->siteassets = $config->urls->root . 'assets/files/';
	$config->sharedaccounts = 'zyxwvu';
	$config->defaultweb = 'WEBORD';
	$config->showonpage = '10';
	$config->showonpageoptions = array('5', '10', '20', '50');
	$config->phoneintl = false;
	$config->allowedcolors = array(
		"#00405d",
		"#062f3c",
		"#2b82ad",
		"#cc7a00",
		"#ff0000",
		"#fbb034",
		"#ffdd00",
		"#c1d82f",
		"#d20962",
		"#f47721",
		"#7ac143",
		"#00a78e",
		"#0079c1",
		"#49176d",
		"#00a0af",
		"#49a942",
		"#020202",
		"#2ad2c9",
		"#d0e100",
		"#00f0f0",
		"#00f000",
		"#f0e000",
		"#00a0f0",
		"#9000f0",
		"#ed1b2e",
		"#6d6e70",
		"#d7d7d8",
		"#b4a996",
		"#ecb731",
		"#8ec06c",
		"#537b35",
		"#c4dff6",
		"#56a0d3",
		"#0091cd",
		"#004b79",
		"#7f181b",
		"#3be8b0",
		"#1aafd0",
		"#6a67ce",
		"#ffb900",
		"#ff7200",
		"#fcb314",
		"#067ab4",
		"#3aa5dc",
		"#16214d",
		"#44c7f4",
		"#eb5424",
		"#d0d2d3",
		"#005387",
		"#8cb811",
		"#fdb813",
		"#88aca1",
		"#000000",
		"#788cb6",
		"#a1a1a4",
		"#8f8f8c",
		"#ffcc2f",
		"#ef5734",
		"#00acee",
		"#2baf2b",
		"#075aaa",
		"#eb2226",
		"#01295c",
		"#efe9e5",
		"#d52685",
		"#553a99",
		"#6cbc35",
		"#fd9f3e",
		"#168eea",
		"#ee4f4f",
		"#fff9ea",
		"#76b852",
		"#323b43",
		"#59626a",
		"#ced7df",
		"#eff3f6",
		"#ec1c24",
		"#fdbd10",
		"#0066b2",
		"#ed7902",
		"#00387b",
		"#bb1e10",
		"#f67828",
		"#237f52",
		"#00aeef",
		"#ed008c",
		"#fff000",
		"#000000",
		"#84754e",
		"#a6192e",
		"#decba5",
		"#000000",
		"#689550",
		"#85c446",
		"#c0de9e",
		"#b9dca4",
		"#830051",
		"#cf0072",
		"#d9e506",
		"#ff7900",
		"#1d1d1b",
		"#ae9a64",
		"#e42313",
		"#8b8c8d",
		"#263f6a",
		"#182b45",
		"#6b0f24",
		"#193725",
		"#334858",
		"#cd595a",
		"#94938f",
		"#a3a7a6",
		"#0085c3",
		"#7ab800",
		"#f2af00",
		"#dc5034",
		"#ce1126",
		"#b7295a",
		"#6e2585",
		"#71c6c1",
		"#5482ab",
		"#009bbb",
		"#444444",
		"#eeeeee",
		"#007dc3",
		"#003f69",
		"#954010",
		"#445c6e",
		"#fdb94e",
		"#f9a852",
		"#f69653",
		"#f38654",
		"#f07654",
		"#ed6856",
		"#ef5956",
		"#ee4c58",
		"#f05d21",
		"#2c5770",
		"#0f723a",
		"#c7c8ca",
		"#7289da",
		"#ffffff",
		"#99aab5",
		"#2c2f33",
		"#e80033",
		"#fdbb30",
		"#ed8b00",
		"#f15d22",
		"#444444",
		"#ea4c89",
		"#8aba56",
		"#ff8833",
		"#007ee5",
		"#7b8994",
		"#47525d",
		"#3d464d",
		"#e53238",
		"#0064d2",
		"#f5af02",
		"#86b817",
		"#314855",
		"#5cc3e8",
		"#ffdb00",
		"#79ceb8",
		"#ff2052",
		"#e6e6e6",
		"#404040",
		"#01b5dd",
		"#0d9ddb",
		"#48b8e7",
		"#efecea",
		"#2c2b2b",
		"#33cc99",
		"#4ba6f5",
		"#fdca30",
		"#f79400",
		"#2dbe60",
		"#7b868a",
		"#2facb2",
		"#166a8f",
		"#3b4446",
		"#525e61",
		"#7b868a",
		"#aeb6b8",
		"#6caddf",
		"#b06010",
		"#004990",
		"#b50938",
		"#660099",
		"#ff6600",
		"#00cc00",
		"#0099cc",
		"#e66000",
		"#ff9500",
		"#ffcb00",
		"#00539f",
		"#ed174f",
		"#fbb040",
		"#efc402",
		"#d4891c",
		"#4dc9f6",
		"#f67019",
		"#f53794",
		"#537bc4",
		"#212425",
		"#718087",
		"#5ba4e5",
		"#9fbb58",
		"#000000",
		"#436f8e",
		"#887d59",
		"#8f9696",
		"#4183c4",
		"#999999",
		"#666666",
		"#333333",
		"#fca326",
		"#fc6d26",
		"#e24329",
		"#554488",
		"#46bc99",
		"#f68d42",
		"#ed1965",
		"#f2f0ed",
		"#4285f4",
		"#34a853",
		"#fbbc05",
		"#ea4335",
		"#0863b5",
		"#fec600",
		"#f39100",
		"#e3001f",
		"#e50064",
		"#954a97",
		"#009ee3",
		"#13a538",
		"#a26eea",
		"#f7afff",
		"#5d70ea",
		"#46b7fd"
	);


/*** INSTALLER CONFIG ********************************************************************/



/**
 * Installer: Database Configuration
 * 
 */
$config->dbHost = 'localhost';
$config->dbName = 'pw_dpluso2';
$config->dbUser = 'cptecomm';
$config->dbPass = 'rghopeless';
$config->dbPort = '3306';

/**
 * Installer: User Authentication Salt 
 * 
 * Must be retained if you migrate your site from one server to another
 * 
 */
$config->userAuthSalt = 'a23729b168ea79f9223fcf29da80235e'; 

/**
 * Installer: File Permission Configuration
 * 
 */
$config->chmodDir = '0755'; // permission for directories created by ProcessWire
$config->chmodFile = '0644'; // permission for files created by ProcessWire 

/**
 * Installer: Time zone setting
 * 
 */
$config->timezone = 'UTC';

/**
 * Installer: Admin theme
 * 
 */
$config->defaultAdminTheme = 'AdminThemeUikit';

/**
 * Installer: Unix timestamp of date/time installed
 * 
 * This is used to detect which when certain behaviors must be backwards compatible.
 * Please leave this value as-is.
 * 
 */
$config->installed = 1553007502;


/**
 * Installer: HTTP Hosts Whitelist
 * 
 */
$config->httpHosts = array('68.232.224.2');


/**
 * Installer: Database Configuration
 * 
 */
$config->dbHost = 'localhost';
$config->dbName = 'pw_dpluso2';
$config->dbUser = 'cptecomm';
$config->dbPass = 'rghopeless';
$config->dbPort = '3306';

/**
 * Installer: User Authentication Salt 
 * 
 * Must be retained if you migrate your site from one server to another
 * 
 */
$config->userAuthSalt = '266fa263a57e77ae21eab9b145ae767c'; 

/**
 * Installer: File Permission Configuration
 * 
 */
$config->chmodDir = '0755'; // permission for directories created by ProcessWire
$config->chmodFile = '0644'; // permission for files created by ProcessWire 

/**
 * Installer: Time zone setting
 * 
 */
$config->timezone = 'UTC';

/**
 * Installer: Admin theme
 * 
 */
$config->defaultAdminTheme = 'AdminThemeUikit';

/**
 * Installer: Unix timestamp of date/time installed
 * 
 * This is used to detect which when certain behaviors must be backwards compatible.
 * Please leave this value as-is.
 * 
 */
$config->installed = 1553007528;


/**
 * Installer: HTTP Hosts Whitelist
 * 
 */
$config->httpHosts = array('68.232.224.2');

